using System;
using System.Collections.Generic;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

[Serializable]
public class OfflineKitchenEarnings
{
    public string kitchenId;
    public long elapsedSeconds;
    public long secondsApplied;
    public float moneyPerSecond;
    public float dishesPerSecond;
    public float moneyEarned;
    public long dishesEarned;
}

[Serializable]
public class OfflineEarningsReport
{
    public long elapsedSeconds;
    public long secondsApplied;
    public float totalMoneyEarned;
    public long totalDishesEarned;
    public List<OfflineKitchenEarnings> kitchens = new List<OfflineKitchenEarnings>();

    public bool HasAnyEarnings
    {
        get { return totalMoneyEarned > 0f || totalDishesEarned > 0L; }
    }
}

/// <summary>
/// Shows the offline earnings report generated by SaveManager.
/// Put this on an active object in each kitchen scene, then assign the panel named offlineEarningsUI.
/// </summary>
public class OfflineEarningsUI : MonoBehaviour
{
    private static OfflineEarningsUI instance;
    private static OfflineEarningsReport pendingReport;

    [Header("Panel")]
    [SerializeField] private GameObject offlineEarningsUI;
    [SerializeField] private TMP_Text earningsText;
    [SerializeField] private Button closeButton;

    [Header("Formatting")]
    [SerializeField] private bool showPerKitchenBreakdown = true;
    [SerializeField] private bool showDishEarnings = false;
    [SerializeField] private string titleLine = "Offline Earnings";

    private void Awake()
    {
        instance = this;

        if (closeButton != null)
        {
            closeButton.onClick.RemoveAllListeners();
            closeButton.onClick.AddListener(Close);
        }

        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(false);
        }

        if (pendingReport != null)
        {
            OfflineEarningsReport report = pendingReport;
            pendingReport = null;
            Show(report);
        }
    }

    private void OnDestroy()
    {
        if (instance == this)
        {
            instance = null;
        }
    }

    public static void ShowReport(OfflineEarningsReport report)
    {
        if (report == null || !report.HasAnyEarnings)
        {
            return;
        }

        if (instance == null)
        {
            pendingReport = report;
            return;
        }

        instance.Show(report);
    }

    public void Show(OfflineEarningsReport report)
    {
        if (report == null || !report.HasAnyEarnings)
        {
            return;
        }

        if (earningsText != null)
        {
            earningsText.text = BuildReportText(report);
        }

        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(true);
        }
    }

    public void Close()
    {
        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(false);
        }
    }

    private string BuildReportText(OfflineEarningsReport report)
    {
        StringBuilder builder = new StringBuilder();

        if (!string.IsNullOrWhiteSpace(titleLine))
        {
            builder.AppendLine(titleLine);
        }

        builder.Append("Away for ");
        builder.AppendLine(FormatDuration(report.elapsedSeconds));
        builder.Append("Total earned: ");
        builder.AppendLine(BigNumberFormatter.FormatMoney((double)report.totalMoneyEarned));

        if (showDishEarnings && report.totalDishesEarned > 0)
        {
            builder.Append("Dishes finished: ");
            builder.AppendLine(BigNumberFormatter.FormatNumber(report.totalDishesEarned));
        }

        if (report.secondsApplied > 0 && report.secondsApplied < report.elapsedSeconds)
        {
            builder.Append("Earnings capped at ");
            builder.AppendLine(FormatDuration(report.secondsApplied));
        }

        if (showPerKitchenBreakdown && report.kitchens != null && report.kitchens.Count > 0)
        {
            builder.AppendLine();

            for (int i = 0; i < report.kitchens.Count; i++)
            {
                OfflineKitchenEarnings kitchen = report.kitchens[i];
                if (kitchen == null)
                {
                    continue;
                }

                builder.Append(FormatKitchenName(kitchen.kitchenId));
                builder.Append(": ");
                builder.Append(BigNumberFormatter.FormatMoney((double)kitchen.moneyEarned));
                builder.Append(" at ");
                builder.Append(BigNumberFormatter.FormatMoney((double)kitchen.moneyPerSecond));
                builder.AppendLine("/sec");

                if (showDishEarnings && kitchen.dishesEarned > 0)
                {
                    builder.Append("  Dishes: ");
                    builder.AppendLine(BigNumberFormatter.FormatNumber(kitchen.dishesEarned));
                }
            }
        }

        return builder.ToString().TrimEnd();
    }

    private string FormatKitchenName(string kitchenId)
    {
        if (string.IsNullOrWhiteSpace(kitchenId))
        {
            return "Kitchen";
        }

        string clean = kitchenId.Replace('_', ' ');

        if (clean.Length == 0)
        {
            return "Kitchen";
        }

        return char.ToUpper(clean[0]) + clean.Substring(1);
    }

    private string FormatDuration(long seconds)
    {
        seconds = Math.Max(0L, seconds);

        long days = seconds / 86400L;
        seconds %= 86400L;

        long hours = seconds / 3600L;
        seconds %= 3600L;

        long minutes = seconds / 60L;
        long remainingSeconds = seconds % 60L;

        if (days > 0)
        {
            return $"{days}d {hours}h {minutes}m";
        }

        if (hours > 0)
        {
            return $"{hours}h {minutes}m";
        }

        if (minutes > 0)
        {
            return $"{minutes}m {remainingSeconds}s";
        }

        return $"{remainingSeconds}s";
    }
}
