using System;
using System.Collections.Generic;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

[Serializable]
public class OfflineKitchenEarnings
{
    public string kitchenId;
    public long elapsedSeconds;
    public long secondsApplied;
    public float moneyPerSecond;
    public float dishesPerSecond;
    public float moneyEarned;
    public long dishesEarned;
}

[Serializable]
public class OfflineEarningsReport
{
    public long elapsedSeconds;
    public long secondsApplied;
    public float totalMoneyEarned;
    public long totalDishesEarned;
    public List<OfflineKitchenEarnings> kitchens = new List<OfflineKitchenEarnings>();

    public bool HasAnyEarnings
    {
        get
        {
            if (kitchens == null)
                return false;

            for (int i = 0; i < kitchens.Count; i++)
            {
                OfflineKitchenEarnings kitchen = kitchens[i];

                if (kitchen == null)
                    continue;

                if (kitchen.moneyEarned > 0f || kitchen.dishesEarned > 0L)
                    return true;
            }

            return false;
        }
    }
}

/// <summary>
/// Shows the offline earnings report generated by SaveManager.
/// Put this on an active object in each kitchen scene, then assign the panel named offlineEarningsUI.
/// </summary>
public class OfflineEarningsUI : MonoBehaviour
{
    private static OfflineEarningsUI instance;
    private static OfflineEarningsReport pendingReport;

    [Header("Panel")]
    [SerializeField] private GameObject offlineEarningsUI;
    [SerializeField] private TMP_Text earningsText;
    [SerializeField] private Button closeButton;

    [Header("Formatting")]
    [SerializeField] private string titleLine = "Offline Earnings";

    private void Awake()
    {
        instance = this;

        if (closeButton != null)
        {
            closeButton.onClick.RemoveAllListeners();
            closeButton.onClick.AddListener(Close);
        }

        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(false);
        }

        if (pendingReport != null)
        {
            OfflineEarningsReport report = pendingReport;
            pendingReport = null;
            Show(report);
        }
    }

    private void OnDestroy()
    {
        if (instance == this)
        {
            instance = null;
        }
    }

    public static void ShowReport(OfflineEarningsReport report)
    {
        if (report == null || !report.HasAnyEarnings)
        {
            return;
        }

        if (instance == null)
        {
            pendingReport = report;
            return;
        }

        instance.Show(report);
    }

    public void Show(OfflineEarningsReport report)
    {
        if (report == null || !report.HasAnyEarnings)
        {
            return;
        }

        if (earningsText != null)
        {
            earningsText.text = BuildReportText(report);
        }

        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(true);
        }
    }

    public void Close()
    {
        if (offlineEarningsUI != null)
        {
            offlineEarningsUI.SetActive(false);
        }
    }

    private string BuildReportText(OfflineEarningsReport report)
    {
        StringBuilder builder = new StringBuilder();

        if (!string.IsNullOrWhiteSpace(titleLine))
        {
            builder.AppendLine(titleLine);
        }

        if (report.kitchens == null || report.kitchens.Count == 0)
        {
            return builder.ToString().TrimEnd();
        }

        for (int i = 0; i < report.kitchens.Count; i++)
        {
            OfflineKitchenEarnings kitchen = report.kitchens[i];

            if (kitchen == null)
            {
                continue;
            }

            if (kitchen.moneyEarned <= 0f && kitchen.dishesEarned <= 0L)
            {
                continue;
            }

            builder.AppendLine(FormatKitchenName(kitchen.kitchenId));

            builder.Append("Money earned: ");
            builder.AppendLine(BigNumberFormatter.FormatMoney((double)kitchen.moneyEarned));

            builder.Append("Dishes done: ");
            builder.AppendLine(BigNumberFormatter.FormatNumber(kitchen.dishesEarned));

            builder.Append("Rate: ");
            builder.Append(BigNumberFormatter.FormatMoney((double)kitchen.moneyPerSecond));
            builder.Append("/sec, ");
            builder.Append(BigNumberFormatter.FormatNumber((double)kitchen.dishesPerSecond));
            builder.AppendLine(" dishes/sec");

            builder.AppendLine();
        }

        return builder.ToString().TrimEnd();
    }

    private string FormatKitchenName(string kitchenId)
    {
        if (string.IsNullOrWhiteSpace(kitchenId))
        {
            return "Kitchen";
        }

        string clean = kitchenId.Replace('_', ' ');

        if (clean.Length == 0)
        {
            return "Kitchen";
        }

        return char.ToUpper(clean[0]) + clean.Substring(1);
    }
}